controller_list:
  - name: fake_arm_bigmama_controller
    type: $(arg fake_execution_type)
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
initial:  # Define initial robot poses.
  - group: arm_bigmama
    pose: StartState