# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm1_bigmama
  joint_model_group_pose: horrizon10
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - Joint_11
    - Joint_12
    - Joint_13
    - Joint_14
    - Joint_21
    - Joint_22
    - Joint_23
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
   - name: arm1_position_controller
     action_ns: follow_joint_trajectory
     type: FollowJointTrajectory
     default: true
     joints:
       - Joint_11
       - Joint_12
       - Joint_13
       - Joint_14
   - name: arm2_position_controller
     action_ns: follow_joint_trajectory
     type: FollowJointTrajectory
     default: true
     joints:  
       - Joint_21
       - Joint_22
       - Joint_23
arm1_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - Joint_11
    - Joint_12
    - Joint_13
    - Joint_14
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      joint_11: {trajectory: 0.1, goal: 0.1}
      joint_12 : {trajectory: 0.1, goal: 0.1}
      joint_13: {trajectory: 0.1, goal: 0.1}
      joint_14: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 1
arm2_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - Joint_21
    - Joint_22
    - Joint_23
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      joint_21: {trajectory: 0.1, goal: 0.1}
      joint_22 : {trajectory: 0.1, goal: 0.1}
      joint_23: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 1
